services:
###################################################################
## Factory
###################################################################
  nours_table.factory:
    class: Nours\TableBundle\Table\Factory\TableFactory

###################################################################
## Extensions
###################################################################
  nours_table.extension.core:
    class: Nours\TableBundle\Table\Extension\CoreExtension
    tags: [ { name: nours_table.extension } ]

  nours_table.extension.pagerfanta:
    class: Nours\TableBundle\Table\Extension\PagerfantaExtension

  nours_table.extension.orm:
    arguments: [ '@doctrine.orm.entity_manager' ]
    class: Nours\TableBundle\Table\Extension\DoctrineORMExtension

  nours_table.extension.form:
    class: Nours\TableBundle\Table\Extension\FormFilterExtension
    arguments: [ '@form.factory' ]


###################################################################
## Twig extension
###################################################################
  nours_table.twig.extension:
    class: Nours\TableBundle\Twig\Extension\TableExtension
    arguments: [ '@nours_table.table_renderer.twig' ]
    tags: [ { name: twig.extension } ]

###################################################################
## Renderer
###################################################################
  nours_table.table_renderer.twig:
    class: Nours\TableBundle\Renderer\TwigRenderer
    arguments: [ '%nours_table.themes%' ]

###################################################################
## Serializer handler
###################################################################
  nours_table.serializer.handler.table_view:
    class: Nours\TableBundle\Serializer\Handler\TableViewHandler
    tags: [ { name: jms_serializer.subscribing_handler } ]