services:
###################################################################
## Factory
###################################################################
  nours_table.factory:
    class: Nours\TableBundle\Factory\TableFactory
    public: true
    arguments:
     - ~  # Table types service locator
     - ~  # Field types service locator

  Nours\TableBundle\Factory\TableFactory:
    alias: nours_table.factory
    public: true

  Nours\TableBundle\Factory\TableFactoryInterface:
    alias: nours_table.factory
    public: true

###################################################################
## Extensions
###################################################################
  nours_table.extension.core:
    class: Nours\TableBundle\Extension\CoreExtension
    arguments: [ '%nours_table.extension.core%' ]
    tags: [ { name: nours_table.extension } ]


###################################################################
## Twig extension
###################################################################
  nours_table.twig.extension:
    class: Nours\TableBundle\Twig\Extension\TableExtension
    tags: [ { name: twig.extension } ]

  nours_table.twig.runtime_loader:
    class: Nours\TableBundle\Twig\Loader\TableRuntimeLoader
    arguments: [ '@service_container' ]

###################################################################
## Renderer
###################################################################
  nours_table.table_renderer.twig:
    class: Nours\TableBundle\Renderer\TwigRenderer
    arguments: [ '@twig', '%nours_table.themes%' ]
    tags: [ { name: twig.runtime } ]