services:
###################################################################
## Factory
###################################################################
  nours_table.types_registry:
    class: Nours\TableBundle\Factory\TypesRegistry

  nours_table.factory:
    class: Nours\TableBundle\Factory\TableFactory
    arguments: [ '@nours_table.types_registry' ]

###################################################################
## Extensions
###################################################################
  nours_table.extension.core:
    class: Nours\TableBundle\Extension\CoreExtension
    arguments: [ %nours_table.extension.core% ]
    tags: [ { name: nours_table.extension } ]

  nours_table.extension.orm:
    arguments: [ '@doctrine.orm.entity_manager' ]
    class: Nours\TableBundle\Extension\DoctrineORMExtension

  nours_table.extension.form:
    class: Nours\TableBundle\Extension\FormExtension
    arguments: [ '@form.factory', %nours_table.form_theme% ]

  nours_table.extension.bootstrap_table:
    class: Nours\TableBundle\Extension\BootstrapTableExtension


###################################################################
## Twig extension
###################################################################
  nours_table.twig.extension:
    class: Nours\TableBundle\Twig\Extension\TableExtension
    arguments: [ '@nours_table.table_renderer.twig' ]
    tags: [ { name: twig.extension } ]

###################################################################
## Renderer
###################################################################
  nours_table.table_renderer.twig:
    class: Nours\TableBundle\Renderer\TwigRenderer
    arguments: [ @service_container, '%nours_table.themes%' ]

###################################################################
## Serializer handler
###################################################################
  nours_table.serializer.handler.table_view:
    class: Nours\TableBundle\Serializer\Handler\TableViewHandler
    tags: [ { name: jms_serializer.subscribing_handler } ]