services:
#  _defaults: { public: true }

###################################################################
## Fields
###################################################################

###################################################################
## Factory
###################################################################
  nours_table.factory:
    class: Nours\TableBundle\Factory\TableFactory
    public: true
    arguments:
     - ~  # Table types service locator
     - ~  # Field types service locator

###################################################################
## Extensions
###################################################################
  nours_table.extension.core:
    class: Nours\TableBundle\Extension\CoreExtension
    arguments: [ '%nours_table.extension.core%' ]
    tags: [ { name: nours_table.extension } ]

  nours_table.extension.orm:
    arguments: [ '@doctrine.orm.entity_manager' ]
    class: Nours\TableBundle\Extension\DoctrineORMExtension

  nours_table.extension.form:
    class: Nours\TableBundle\Extension\FormExtension
    arguments: [ '@form.factory', '%nours_table.form_theme%' ]

  nours_table.extension.bootstrap_table:
    class: Nours\TableBundle\Extension\BootstrapTableExtension


###################################################################
## Twig extension
###################################################################
  nours_table.twig.extension:
    class: Nours\TableBundle\Twig\Extension\TableExtension
    tags: [ { name: twig.extension } ]

  nours_table.twig.runtime_loader:
    class: Nours\TableBundle\Twig\Loader\TableRuntimeLoader
    arguments: [ '@service_container' ]

###################################################################
## Renderer
###################################################################
  nours_table.table_renderer.twig:
    class: Nours\TableBundle\Renderer\TwigRenderer
    arguments: [ '@twig', '%nours_table.themes%' ]
    tags: [ { name: twig.runtime } ]

###################################################################
## Serializer handler
###################################################################
  nours_table.serializer.handler.table_view:
    class: Nours\TableBundle\Serializer\Handler\TableViewHandler
    tags: [ { name: jms_serializer.subscribing_handler } ]