dist: trusty
language: php

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.4'
    - php: 7.2
      env: SYMFONY_VERSION='^5.4'
    - php: 7.4
      env: SYMFONY_VERSION='^3.4'
    - php: 7.4
      env: SYMFONY_VERSION='^4.4'
    - php: 7.4
      env: SYMFONY_VERSION='^5.4'
    - php: 8.0
      env: SYMFONY_VERSION='^6.0'

install:
  - phpenv config-add travis.php.ini
  - php -ini | grep memory_limit

before_script:
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --dev
  - vendor/bin/phpunit --version

script: vendor/bin/phpunit