dist: trusty
language: php
php:
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*

install:
  - phpenv config-add travis.php.ini
  - php -ini | grep memory_limit

before_script:
  - composer require "symfony/symfony:${SYMFONY_VERSION}" --dev
  - vendor/bin/phpunit --version

script: vendor/bin/phpunit